import 'package:flutter_test/flutter_test.dart';
import 'package:harmonymusic/services/podcast_service.dart';

void main() {
  group('parseTranscriptDocument', () {
    test('SRT: parses timestamps and coalesces mid-sentence cues', () {
      const srt = '''
1
00:00:00,000 --> 00:00:02,500
Welcome back to the show,

2
00:00:02,500 --> 00:00:04,000
today we talk transcripts.

3
00:00:06,000 --> 00:00:08,000
Second paragraph starts here.
''';
      final cues = PodcastService.parseTranscriptDocument(srt, type: 'application/srt');
      expect(cues.length, 2);
      expect(cues[0].startSec, 0.0);
      expect(cues[0].text,
          'Welcome back to the show, today we talk transcripts.');
      expect(cues[1].startSec, 6.0);
      expect(cues[1].endSec, 8.0);
    });

    test('VTT: handles header, MM:SS times and <v Speaker> tags', () {
      const vtt = '''WEBVTT

NOTE generated by test

00:01.000 --> 00:03.000
<v Alice>Hello there!

00:04.900 --> 00:07.000
<v Bob>Hi Alice.
''';
      final cues = PodcastService.parseTranscriptDocument(vtt);
      expect(cues.length, 2);
      expect(cues[0].startSec, 1.0);
      expect(cues[0].speaker, 'Alice');
      expect(cues[0].text, 'Hello there!');
      expect(cues[1].speaker, 'Bob');
    });

    test('Podcasting 2.0 JSON: segments with speakers', () {
      const json = '''
{"version":"1.0.0","segments":[
  {"speaker":"Host","startTime":0.5,"endTime":3.2,"body":"First line."},
  {"speaker":"Guest","startTime":4.0,"endTime":6.0,"body":"Second line."}
]}''';
      final cues = PodcastService.parseTranscriptDocument(json);
      expect(cues.length, 2);
      expect(cues[0].speaker, 'Host');
      expect(cues[0].startSec, 0.5);
      expect(cues[1].text, 'Second line.');
    });

    test('plain text: untimed paragraphs marked with startSec -1', () {
      const txt = 'First paragraph of the episode.\n\nSecond paragraph.';
      final cues = PodcastService.parseTranscriptDocument(txt);
      expect(cues.length, 2);
      expect(cues.first.startSec, -1);
      expect(cues[1].text, 'Second paragraph.');
    });

    test('HTML: tags stripped into paragraphs', () {
      const html =
          '<html><body><p>Para one.</p><p>Para <b>two</b>.</p></body></html>';
      final cues =
          PodcastService.parseTranscriptDocument(html, type: 'text/html');
      expect(cues.length, 2);
      expect(cues[0].text, 'Para one.');
      expect(cues[1].text, 'Para two.');
    });

    test('speaker change is never merged even within the gap window', () {
      const srt = '''
1
00:00:00,000 --> 00:00:01,000
A: I think

2
00:00:01,000 --> 00:00:02,000
B: no way
''';
      final cues = PodcastService.parseTranscriptDocument(srt, type: 'srt');
      expect(cues.length, 2);
      expect(cues[0].speaker, 'A');
      expect(cues[1].speaker, 'B');
    });
  });
}
