"""Generate every Riff logo asset from one vector definition.

    pip install cairosvg pillow
    python3 tooling/logo/generate_logo.py .

Writes the adaptive launcher icon (vector foreground/monochrome + colour
background), legacy launcher PNGs, the status-bar notification icon, the
splash icon, assets/icons/icon.png / icon.ico and the fastlane store icon.
"""
import io, os, re, sys
import cairosvg
from PIL import Image, ImageDraw

# Guitar pick in a 108x108 adaptive-icon viewport (launcher safe zone is the
# central 66dp circle). Colours match the app accent on Pitch Black.
GREEN = '#1DB954'
INK = '#0B0B0C'

# Guitar pick: a rounded triangle (flat-ish top, round shoulders, blunt
# tip) so it reads as a pick, not a map pin, with a play triangle cut out.
PICK = ('M36,27 C45,24.5 63,24.5 72,27 '
        'C80,29.5 82.5,36 79.5,43 '
        'C74,56 64,70 57.5,78.5 '
        'C55.7,80.8 52.3,80.8 50.5,78.5 '
        'C44,70 34,56 28.5,43 '
        'C25.5,36 28,29.5 36,27 Z')
# Wound opposite to PICK, so the cut-out also shows with the default
# non-zero fill rule (Android < 7 ignores fillType="evenOdd").
PLAY = ('M49.5,51.7 C49.5,53.8 51.8,55.1 53.6,54 L63.4,48.1 '
        'C65.1,47 65.1,44.5 63.4,43.4 L53.6,37.5 '
        'C51.8,36.4 49.5,37.7 49.5,39.8 Z')


REPO = sys.argv[1]
RES = f'{REPO}/android/app/src/main/res'

NUM = re.compile(r'[MCLZ]|-?\d+(?:\.\d+)?')

def bake(d, scale, tx, ty, about=None):
    """Apply scale (about a point) + translate to an absolute M/C/L/Z path."""
    ax, ay = about or (0, 0)
    out, coords = [], []
    for tok in NUM.findall(d):
        if tok in 'MCLZ':
            out.append(tok)
            continue
        coords.append(float(tok))
        if len(coords) == 2:
            x, y = coords
            x = ax + (x - ax) * scale + tx
            y = ay + (y - ay) * scale + ty
            out.append(f'{x:.2f},{y:.2f}')
            coords = []
    return ' '.join(out)

# Play cut-out a little larger so it survives small sizes.
play = bake(PLAY, 1.15, 0, 0, about=(56.5, 45.75))
# Glyph into the 108dp adaptive viewport, inside the 66dp safe circle.
def glyph_path(scale=0.86, cx=54, cy=54, vcy=51):
    t = lambda p: bake(p, scale, cx - 54, cy - vcy, about=(54, vcy))
    return f'{t(PICK)} {t(play)}'

GLYPH_108 = glyph_path()

def vector(path, fill, size_dp, viewport=108, extra=''):
    return f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Riff logo: guitar pick with a play cut-out. Generated by
     tooling/logo/generate_logo.py; edit that, not this file. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{size_dp}dp"
    android:height="{size_dp}dp"
    android:viewportWidth="{viewport}"
    android:viewportHeight="{viewport}"{extra}>
    <path
        android:fillColor="{fill}"
        android:fillType="evenOdd"
        android:pathData="{path}" />
</vector>
'''

def svg(path, fill, bg=None, viewport=108, radius=None):
    bgel = ''
    if bg:
        r = f' rx="{radius}"' if radius else ''
        bgel = f'<rect width="{viewport}" height="{viewport}"{r} fill="{bg}"/>'
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {viewport} {viewport}">'
            f'{bgel}<path fill="{fill}" fill-rule="evenodd" d="{path}"/></svg>')

def png(svg_text, px):
    data = cairosvg.svg2png(bytestring=svg_text.encode(), output_width=px, output_height=px)
    return Image.open(io.BytesIO(data)).convert('RGBA')

def write(path, text):
    with open(path, 'w') as f:
        f.write(text)

# 1. Adaptive icon: solid background colour + vector foreground/monochrome.
write(f'{RES}/drawable/ic_launcher_foreground.xml', vector(GLYPH_108, GREEN, 108))
write(f'{RES}/drawable/ic_launcher_monochrome.xml', vector(GLYPH_108, '#FFFFFFFF', 108))
write(f'{RES}/mipmap-anydpi-v26/ic_launcher.xml', '''<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
  <background android:drawable="@color/ic_launcher_background"/>
  <foreground android:drawable="@drawable/ic_launcher_foreground"/>
  <monochrome android:drawable="@drawable/ic_launcher_monochrome"/>
</adaptive-icon>
''')
colors = f'{RES}/values/colors.xml'
c = open(colors).read()
if 'ic_launcher_background' not in c:
    c = c.replace('</resources>', f'    <color name="ic_launcher_background">{INK}</color>\n</resources>')
    write(colors, c)

# 2. Legacy (API < 26) launcher PNGs: the visible 72dp of the adaptive
#    icon, rounded like a modern launcher tile.
for folder, px in {'mdpi': 48, 'hdpi': 72, 'xhdpi': 96, 'xxhdpi': 144, 'xxxhdpi': 192}.items():
    d = f'{RES}/mipmap-{folder}'
    for old in ('ic_launcher_background.png', 'ic_launcher_foreground.png', 'ic_launcher_monochrome.png'):
        if os.path.exists(f'{d}/{old}'):
            os.remove(f'{d}/{old}')
    big = png(svg(GLYPH_108, GREEN, INK), px * 108 // 72 * 4)
    n = big.size[0]
    inset = n * 18 // 108
    big = big.crop((inset, inset, n - inset, n - inset))
    mask = Image.new('L', big.size, 0)
    ImageDraw.Draw(mask).rounded_rectangle((0, 0, big.size[0] - 1, big.size[1] - 1),
                                           radius=big.size[0] * 22 // 100, fill=255)
    tile = Image.new('RGBA', big.size, (0, 0, 0, 0))
    tile.paste(big, (0, 0), mask)
    tile.resize((px, px), Image.LANCZOS).save(f'{d}/ic_launcher.png')

# 3. Notification (status bar) icon: white silhouette filling a 24dp box.
def bbox(path):
    pts = [tuple(map(float, p.split(','))) for p in re.findall(r'-?\d+\.\d+,-?\d+\.\d+', path)]
    xs, ys = [p[0] for p in pts], [p[1] for p in pts]
    return min(xs), min(ys), max(xs), max(ys)
x0, y0, x1, y1 = bbox(GLYPH_108)
side = max(x1 - x0, y1 - y0)
s = 21.0 / side
stat = bake(GLYPH_108, s, 12 - (x0 + x1) / 2 * s, 12 - (y0 + y1) / 2 * s)
write(f'{RES}/drawable/ic_stat_riff.xml', vector(stat, '#FFFFFFFF', 24, viewport=24))

# 4. Splash icon (API 31+ windowSplashScreenAnimatedIcon and the pre-31
#    launch background): 240dp canvas, glyph inside the 160dp circle.
write(f'{RES}/drawable/animated_splash_icon.xml', vector(GLYPH_108, GREEN, 240))

# 5. In-app / desktop logo files.
tile = png(svg(bake(GLYPH_108, 108 / 72, -18 * 108 / 72, -18 * 108 / 72), GREEN, INK, radius=24), 512)
tile.save(f'{REPO}/assets/icons/icon.png')
# Store listing icon (F-Droid / IzzyOnDroid read fastlane metadata).
tile.save(f'{REPO}/fastlane/metadata/android/en-US/images/icon.png')
tile.save(f'{REPO}/assets/icons/icon.ico', sizes=[(16, 16), (24, 24), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)])
print('done')
