"""Generate every Riff logo asset from one vector definition.

    pip install cairosvg pillow
    python3 tooling/logo/generate_logo.py .

Writes the adaptive launcher icon (vector foreground/monochrome + colour
background), legacy launcher PNGs, the status-bar notification icon, the
splash icon, assets/icons/icon.png / icon.ico and the fastlane store icon.
"""
import io, os, re, sys
import cairosvg
from PIL import Image, ImageDraw

# Glyph in a 108x108 adaptive-icon viewport (launcher safe zone is the
# central 66dp circle). Colours match the app accent on Pitch Black.
GREEN = '#1DB954'
INK = '#0B0B0C'

# Four rounded equalizer bars (short, tall, medium, short), centred in the
# 108dp viewport and well inside the 66dp safe circle.
BAR_WIDTH = 8
BARS = [(33, 16), (45.5, 40), (58, 28), (70.5, 12)]  # (left x, height)
K = 0.5523  # cubic approximation of a quarter circle


def pill(x, y, w, h):
    """Rounded bar as an absolute M/C/L/Z path (VectorDrawable-safe)."""
    r = w / 2
    k = K * r
    return (f'M{x},{y + r} C{x},{y + r - k} {x + r - k},{y} {x + r},{y} '
            f'C{x + r + k},{y} {x + w},{y + r - k} {x + w},{y + r} '
            f'L{x + w},{y + h - r} '
            f'C{x + w},{y + h - r + k} {x + r + k},{y + h} {x + r},{y + h} '
            f'C{x + r - k},{y + h} {x},{y + h - r + k} {x},{y + h - r} Z')


GLYPH_108 = ' '.join(pill(x, 54 - h / 2, BAR_WIDTH, h) for x, h in BARS)
NUM = re.compile(r'[MCLZ]|-?\d+(?:\.\d+)?')


def bake(d, scale, tx, ty, about=None):
    """Apply scale (about a point) + translate to an absolute M/C/L/Z path."""
    ax, ay = about or (0, 0)
    out, coords = [], []
    for tok in NUM.findall(d):
        if tok in 'MCLZ':
            out.append(tok)
            continue
        coords.append(float(tok))
        if len(coords) == 2:
            x, y = coords
            x = ax + (x - ax) * scale + tx
            y = ay + (y - ay) * scale + ty
            out.append(f'{x:.2f},{y:.2f}')
            coords = []
    return ' '.join(out)


GLYPH_108 = bake(GLYPH_108, 1, 0, 0)

REPO = sys.argv[1]
RES = f'{REPO}/android/app/src/main/res'


def vector(path, fill, size_dp, viewport=108, extra=''):
    return f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Riff logo: equalizer bars. Generated by
     tooling/logo/generate_logo.py; edit that, not this file. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{size_dp}dp"
    android:height="{size_dp}dp"
    android:viewportWidth="{viewport}"
    android:viewportHeight="{viewport}"{extra}>
    <path
        android:fillColor="{fill}"
        android:fillType="evenOdd"
        android:pathData="{path}" />
</vector>
'''

def svg(path, fill, bg=None, viewport=108, radius=None):
    bgel = ''
    if bg:
        r = f' rx="{radius}"' if radius else ''
        bgel = f'<rect width="{viewport}" height="{viewport}"{r} fill="{bg}"/>'
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {viewport} {viewport}">'
            f'{bgel}<path fill="{fill}" fill-rule="evenodd" d="{path}"/></svg>')

def png(svg_text, px):
    data = cairosvg.svg2png(bytestring=svg_text.encode(), output_width=px, output_height=px)
    return Image.open(io.BytesIO(data)).convert('RGBA')

def write(path, text):
    with open(path, 'w') as f:
        f.write(text)

# 1. Adaptive icon: solid background colour + vector foreground/monochrome.
write(f'{RES}/drawable/ic_launcher_foreground.xml', vector(GLYPH_108, GREEN, 108))
write(f'{RES}/drawable/ic_launcher_monochrome.xml', vector(GLYPH_108, '#FFFFFFFF', 108))
write(f'{RES}/mipmap-anydpi-v26/ic_launcher.xml', '''<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
  <background android:drawable="@color/ic_launcher_background"/>
  <foreground android:drawable="@drawable/ic_launcher_foreground"/>
  <monochrome android:drawable="@drawable/ic_launcher_monochrome"/>
</adaptive-icon>
''')
colors = f'{RES}/values/colors.xml'
c = open(colors).read()
if 'ic_launcher_background' not in c:
    c = c.replace('</resources>', f'    <color name="ic_launcher_background">{INK}</color>\n</resources>')
    write(colors, c)

# 2. Legacy (API < 26) launcher PNGs: the visible 72dp of the adaptive
#    icon, rounded like a modern launcher tile.
for folder, px in {'mdpi': 48, 'hdpi': 72, 'xhdpi': 96, 'xxhdpi': 144, 'xxxhdpi': 192}.items():
    d = f'{RES}/mipmap-{folder}'
    for old in ('ic_launcher_background.png', 'ic_launcher_foreground.png', 'ic_launcher_monochrome.png'):
        if os.path.exists(f'{d}/{old}'):
            os.remove(f'{d}/{old}')
    big = png(svg(GLYPH_108, GREEN, INK), px * 108 // 72 * 4)
    n = big.size[0]
    inset = n * 18 // 108
    big = big.crop((inset, inset, n - inset, n - inset))
    mask = Image.new('L', big.size, 0)
    ImageDraw.Draw(mask).rounded_rectangle((0, 0, big.size[0] - 1, big.size[1] - 1),
                                           radius=big.size[0] * 22 // 100, fill=255)
    tile = Image.new('RGBA', big.size, (0, 0, 0, 0))
    tile.paste(big, (0, 0), mask)
    tile.resize((px, px), Image.LANCZOS).save(f'{d}/ic_launcher.png')

# 3. Notification (status bar) icon: white silhouette filling a 24dp box.
def bbox(path):
    pts = [tuple(map(float, p.split(','))) for p in re.findall(r'-?\d+\.\d+,-?\d+\.\d+', path)]
    xs, ys = [p[0] for p in pts], [p[1] for p in pts]
    return min(xs), min(ys), max(xs), max(ys)
x0, y0, x1, y1 = bbox(GLYPH_108)
side = max(x1 - x0, y1 - y0)
s = 21.0 / side
stat = bake(GLYPH_108, s, 12 - (x0 + x1) / 2 * s, 12 - (y0 + y1) / 2 * s)
write(f'{RES}/drawable/ic_stat_riff.xml', vector(stat, '#FFFFFFFF', 24, viewport=24))

# 4. Splash icon (API 31+ windowSplashScreenAnimatedIcon and the pre-31
#    launch background): 240dp canvas, glyph inside the 160dp circle.
write(f'{RES}/drawable/animated_splash_icon.xml', vector(GLYPH_108, GREEN, 240))

# 5. In-app / desktop logo files.
tile = png(svg(bake(GLYPH_108, 108 / 72, -18 * 108 / 72, -18 * 108 / 72), GREEN, INK, radius=24), 512)
tile.save(f'{REPO}/assets/icons/icon.png')
# Store listing icon (F-Droid / IzzyOnDroid read fastlane metadata).
tile.save(f'{REPO}/fastlane/metadata/android/en-US/images/icon.png')
tile.save(f'{REPO}/assets/icons/icon.ico', sizes=[(16, 16), (24, 24), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)])
print('done')
